---
title: "NonStGM Testing"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)
library(quantmod)
library(tidygraph)
library(ggraph)
library(eegkit)
```

```{r}
#10 major tech companies
tickers = c("AAPL", "MSFT", "GOOGL", "AMZN", "META", 
             "NVDA", "TSLA", "AMD", "INTC", "CRM")


start_date = "2022-01-01"
end_date = "2024-01-01"

stock_data = new.env()
getSymbols(tickers, src = "yahoo", from = start_date, to = end_date, env = stock_data)

prices = do.call(merge, eapply(stock_data, Ad))
colnames(prices) = gsub(".Adjusted", "", colnames(prices))

prices = prices[, tickers]

log_returns = diff(log(prices))[-1, ]

log_returns = na.omit(log_returns)

x_finance = as.matrix(log_returns)
```
```{r}
alpha = 0.05
nu = 2
L = 1
p_tech = ncol(x_finance)

significant_edges_tech = NonStGM(x_finance, "Kernel_Quadratic", nu, L, alpha = alpha)

print(significant_edges_tech)

plot_network(significant_edges_tech, p_tech, 
             title = paste0("Tech Stocks Network (alpha = ", alpha, ")"))
```

```{r}
summary_table = tibble(
  Metric = c("Number of Variables (p)",
             "Number of Observations (n)",
             "Significance Level (alpha)",
             "Number of Significant Edges",
             "Network Density"),
  Value = c(p_tech,
            nrow(x_finance),
            alpha,
            nrow(significant_edges_tech),
            round(nrow(significant_edges_tech) / ((p_tech * (p_tech - 1) / 2)+ p_tech), 4))
)

knitr::kable(summary_table, caption = "Analysis Summary")
```


```{r}
channels_of_interest = c("FP1", "FP2", "F7", "F3", "FZ", "F4", "F8",
  "T7", "C3", "CZ", "C4", "T8")

#channels_of_interest = c(
  #"FP1", "FP2", "F7", "F3", "FZ", "F4", "F8",
  #"T7", "C3", "CZ", "C4", "T8",
  #"P7", "P3", "PZ", "P4", "P8",
  #"O1", "OZ", "O2"
#)

x_eeg <- eegdata |>
  dplyr::filter(
    channel %in% channels_of_interest,
    subject == unique(eegdata$subject)[1],
    condition == unique(eegdata$condition)[1] 
  ) |>
  dplyr::arrange(trial, time) |>
  dplyr::select(trial, time, channel, voltage) |>
  # Ensure no duplicates
  dplyr::distinct(trial, time, channel, .keep_all = TRUE) |>
  tidyr::pivot_wider(
    names_from = channel,
    values_from = voltage
  ) |>
  dplyr::arrange(trial, time) |>
  dplyr::select(all_of(channels_of_interest)) |>
  as.matrix()
```

```{r}
alpha = 0.05
nu = 2
L = 1
p_eeg = ncol(x_eeg)

significant_edges_eeg = NonStGM(x_eeg, "Kernel_Quadratic", nu, L, alpha = alpha)
print(significant_edges_eeg)
plot_network(significant_edges_eeg, p_eeg,
             title = paste0("EEG Brain Connectivity Network (alpha = ", alpha, ")"))
```

```{r}
summary_table_eeg <- tibble(
  Metric = c("Number of Channels (p)",
             "Number of Samples (n)",
             "Significance Level (alpha)",
             "Number of Significant Connections",
             "Network Density"),
  Value = c(p_eeg,
            nrow(x_eeg),
            alpha,
            nrow(significant_edges_eeg),
            round(nrow(significant_edges_eeg) / ((p_eeg * (p_eeg - 1)  / 2) + p_eeg), 4))
)
knitr::kable(summary_table_eeg, caption = "EEG Brain Network Analysis Summary")
```

